# Generated by Django 6.0.6 on 2026-06-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('venue_address', models.TextField()),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=30)),
                ('lead', models.OneToOneField(blank=True, help_text='Link to the lead that generated this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
