# Generated by Django 6.0.6 on 2026-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('private_party', 'Private Party'), ('birthday', 'Birthday Celebration'), ('other', 'Other Special Event')], default='private_party', max_length=50)),
                ('event_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('budget', models.CharField(help_text='Estimated budget range or amount', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Additional details, dietary requests, etc.')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted (Booked)'), ('lost', 'Lost')], default='new', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
